export enum ACTION_TYPES {
    COMPANY_DETAILS_REQUEST = 'COMPANIES/COMPANY_DETAILS_REQUEST',
    COMPANY_DETAILS_REQUEST_SUCCESS = 'COMPANIES/COMPANY_DETAILS_REQUEST_SUCCESS',
    COMPANY_DETAILS_REQUEST_FAIL = 'COMPANIES/COMPANY_DETAILS_REQUEST_FAIL',
}
