export enum ACTION_TYPES {
    COMPANY_DETAILS_REQUEST = 'COMPANIES/COMPANY_DETAILS_REQUEST',
    COMPANY_DETAILS_REQUEST_SUCCESS = 'COMPANIES/COMPANY_DETAILS_REQUEST_SUCCESS',
    COMPANY_DETAILS_REQUEST_FAIL = 'COMPANIES/COMPANY_DETAILS_REQUEST_FAIL',
    SET_SELECTED_SERVICE_ID = 'COMPANIES/SET_SELECTED_SERVICE_ID',
    SLOTS_REQUEST = 'COMPANIES/SLOTS_REQUEST',
    SLOTS_REQUEST_SUCCESS = 'COMPANIES/SLOTS_REQUEST_SUCCESS',
    SLOTS_REQUEST_FAIL = 'COMPANIES/SLOTS_REQUEST_FAIL',
    SET_SELECTED_SLOT_ID = 'COMPANIES/SET_SELECTED_SLOT_ID',
}
