export enum ACTION_TYPES {
    EVENTS_REQUEST = 'USERS/EVENTS_REQUEST',
    EVENTS_REQUEST_SUCCESS = 'USERS/EVENTS_REQUEST_SUCCESS',
    EVENTS_REQUEST_FAIL = 'USERS/EVENTS_REQUEST_FAIL',
    SET_SELECTED_EVENT = 'USERS/SET_SELECTED_EVENT',
}
